### ISSUE TITLE
Equihash crashing inno3d GTX 1080 Twin X2 (Micron memory)

### ISSUE THREAD

**Issue by zokocx** [OhGodACompany/OhGodAnETHlargementPill#16]
Just to say I'm really skeptical how this can improve loosely timming on 1080, which by speculation is culprit for Ethash bad hashrate on this no-ti cards.
And as we knows timings are handled in bios, driver just communicated through bios interfaces, and if there is some command to set in driver to override memory and you found it, then excellent job this will land you a job.

For now I'm interested to mine Equihash coins, which depends partially on memory, so lets start there.
Will try some Ethash coin on weekend to try to confirm this.

So was trying if there is any effect with bminer 6.1.0 and dstm's ZCash / Equihash Nvidia Miner 0.6.
biminer crashed with cuda errors, and dstm's crash violently (now error). Manage to see 0 Sols/s in bminer, GPU usage 0%.

OS restart helps to revert to stock, I assume you are doing some dll injections in nvidia driver process.
I hope that's all, will doing close monitoring of rig if there are any foreign activitis on rig,
don't mine to reinstall perfectly tweaked rig and set it up again, but don't want to waste time if you pill has no really unwanted side effects.

So for feedback:
OS: Windows Server 2016 (version 1607)
Nvidia driver: 391.01

http://gpuz.techpowerup.com/18/04/25/4cb.png

[GP104.zip](https://github.com/OhGodACompany/OhGodAnETHlargementPill/files/1949129/GP104.zip)
[GP104-same.zip](https://github.com/OhGodACompany/OhGodAnETHlargementPill/files/1949130/GP104-same.zip)
(all cards are same, with same memory vendor so I assume that these to sample BIOSes are same).

Will watching this tool and ANN for more confirmation, I hope this is not some scam (few high *hashrate* dudes says nothing that is 100% confirmed).

**Comment by OhGodABird** [comment]
While OhGodACompany is well... a company, therefore it's not exactly just getting jobs, as a member of the team working on the pill I thank you, your wish already came true, I'm working for the most innovative company in its segment.

OhGodAn**ETH**LargementPill was made for helping people suffering from ED (Ethereum Dysfunction). While it may cure other issues as well, they are not supported.

If you face issues with Ethereum too, your 1080 may be an older model, which likely needs --revA to be used as described in the prescription.

I can't assist you in your speculation regarding the internals of the pill, the exact method used will not be revealed in order to honor agreements. If you are interested in learning, I recommend you to check out other open-source tools provided by OhGodACompany.

**Comment by OhGodAGirl** [comment]
It won't affect Equihash.

Please study how the Equihash algorithm works. 

It's called _**ETHlargement**_, not EQUILargement (thanks, PL3!).

**Comment by Yurexxx** [comment]
You can call that pill as Cryptonilargement too - 20% extra Mhs on MoneroV7!!!

**Comment by zokocx** [comment]
Ok, thanks for clarification.
I thought is general and improving memory performance.

Will try this when I decided to mine some Ethash or Cryptonight V7.
