### ISSUE TITLE
MSI 1080ti Gaming 11G specific

### ISSUE THREAD

**Issue by lyolyalya** [OhGodACompany/OhGodAnETHlargementPill#19]
yes.you were right about cards OC and Powerlimit.
with PL 80|GPU+150|MEM+500 i get 54.4 MHS(GPU core is 1600 MHZ)
with PL 75|GPU+150|MEM+500 i get 50.4 MHS(GPU core is 1342 MHZ)
with PL 65|GPU+220|MEM+500 i get 34.5 MHS(GPU core is 970 MHZ)

so PL is the main thing in this case.you need to mention this in readme i guess.

remark.Zotac Geforce GTX 1080 8192MB (ZT-P10800D-10B OEM) is doing well even with PL65|GPU+160|MEM+500(GPU core is 1600 MHZ) - 38MHS so i guess you need to work with 1080ti more.cause there are same problems on other people and many miners are using PL65-70 something about  to mine eth only.

in my case only ETH with a pill dropping GPU clock so much.other algos GPU clock +220(around 1720 MHZ or so) is doing fine.

http://img.techpowerup.org/180426/p1kalmig2k.jpg

**Comment by OhGodABird** [comment]
The issue is not directly related to the pill, because the higher power usage is just the result of better resource utilization. The pill is also not changing either the clocks or the power limit, therefore if users decide to change these values, it's their responsibility to have appropriate values considering both the workload and the requirements of individual GPUs.

As you are already using MSI Afterburner, I suggest checking out the voltage/frequency curve editor which can be used to limit the maximum clock and give the GPU the freedom of using as much power as it requires for the applied workload within reasonable limits. You can read more about it [here](http://www.guru3d.com/news-story/download-msi-afterburner-4-3-beta-14.html), starting from the line about "GPU Boost 3.0 technology".

**Comment by lyolyalya** [comment]
1080ti and 1080 has same PL and OC.but why 1080ti is dropping GPU clock and 1080 not with your utility?i'm not demanding anything, just want to help but if you think that there is no problem then ok.

**Comment by OhGodABird** [comment]
Power limit on Windows is percentage based on the limit specified in the BIOS of the GPU, therefore in theory it's possible to have 2 of the same GPU models with the same percentage based limit perform wildly differently because of different BIOSes. This issue makes it hard to have a generic recommendation, and that's why I recommended working on the voltage/frequency curve, which is operating on absolute values.

We are thankful for every kind of feedback, but your issue was only the power limitation you imposed on your GPU, which has the straightforward consequence of potentially handicapping performance of any kind of workload on that GPU.
