### ISSUE TITLE
Dosage and side effects

### ISSUE THREAD

**Issue by zutata** [OhGodACompany/OhGodAnETHlargementPill#28]
My cards suffer from perpetual hashrate sag.
Wondering if I can get some details on the dosage. 

My rig has the following cards installed in windows:
Gpu 0= 1080Ti 
Gpu 1=1060
Gpu 2= 1070
Gpu 3= 1060
Gpu 4= 1060
Gpu 5= 1080Ti
Gpu 6=1080Ti

Can some please prescribe the exact dose needed to run these cards. 
Any help with the command line arguments will be greatly appreciated.
I have Claymore 11.7 installed on Window 10. Driver 388.xx

Also second question:
What are the long and short term side effects of this pill. 
Will the cards lifespan be affected? Is the card adversely effected by this in any way. 
Are my cards going to get a fever or diarrhoea from an overdose?
 
Thanks.

**Comment by OhGodABird** [comment]
Good to see you are finally visiting the medical professionals with your issue, even if the pill is generally safe to be taken without medical knowledge, only causing short term blue vision if not handled with enough care.

Currently I am only offering a cure for GPU 0, 5, and 6, but their probability of full recovery is very high.
I'm prescribing you OhGodAnETHlargementPill-r2.exe, which can be taken any time, but it's recommended to take it after boot. Take just one pill, keep it working in your system, and do not take another one while the previous one is still not flushed out by a reboot or any other effect stopping the dosing process.
You likely won't encounter issues with your setup by just taking the pill without arguments, just don't forget not to get high with your clocks without knowing your limits like you would need to do with any kind of new medication.

When the pill is taken the right way, overwhelming euphoria can be expected in the short term, then be prepared not to be shocked by the long-forgotten sight of bills paid in time in the long term.

As the GPUs' resources are going to be utilized more efficiently, it is going to work harder, which can result in them getting hot. In poor conditions it can result in a happy but unfortunately short lifespan, while in a loving home, hot GPUs always attract a lot of fans, which makes them cool.

Taking just one pill at a time as prescribed without any other medicine will not result in an issue. If your clocks tend to get high, it's advised to monitor the health of the miner, and also ask the pool how impressive your actual hashrate is, because getting too high distorts your perception.
