### ISSUE TITLE
Its Normal ?

### ISSUE THREAD

**Issue by frankabb** [OhGodACompany/OhGodAnETHlargementPill#82]
This is Normal that the effectiveness of the Hash Rate is always below the reported and average..

![hash rate 1080ti](https://user-images.githubusercontent.com/38145947/42136329-1f826a24-7d27-11e8-8114-4258385d65b1.png)

**Comment by OhGodABird** [comment]
Depending on the environment, it could be even better than expected, and as you gave zero information about your hardware, I can only make assumptions regarding the situation.

If you use overly overclocked 1080s in a fan-less enclosure with the cheapest, weakest hardware you could find which is also connected through a spotty 2G mobile data network, then your result is actually impressive.

**Comment by frankabb** [comment]
Greetings and thanks for responding congratulations for the work you are doing.

I'm sorry I thought I sent the information

4 Rigs
1.- Platform with 6 AORUS cards GeForce® GTX 1080 Ti 11G
2.- Platform with 5 AORUS cards GeForce® GTX 1080 Ti 11G
3.- Platform with 5 AORUS cards GeForce® GTX 1080 Ti 11G
4.- Platform with 5 EVGA cards GeForce® GTX 1070 8GB

![hash rate 1080ti workers](https://user-images.githubusercontent.com/38145947/42137070-f5e3b940-7d33-11e8-8059-e1a780540fa6.png)
![hash rate 1080ti workers](https://user-images.githubusercontent.com/38145947/42137124-e434c576-7d34-11e8-9260-29d71cd807ed.png)

**Comment by OhGodABird** [comment]
Your latency is high, and if your overclock is this simple, I guess it isn't well-tuned.
I suggest trying and comparing the following setups:
- No OC, no pill: this will show how much can be blamed on your internet connection or the pool itself
- No OC, pill: this will show if your clocks are too high

Do note that it's pointless to test on the GTX 1070s, because the pill doesn't affect that.

**Comment by OhGodABird** [comment]
The issue seems to be abandoned, therefore I'm closing it.
